# https://docs.docker.com/compose/compose-file/compose-versioning/
version: "3.7"

# https://docs.docker.com/compose/compose-file/

services:

  sidecar:
    image: "${SIDECAR_APP_IMAGE_NAME}"
    # ports:
    #   - 8090:8090
    environment:
      BUILD_HASH:
      BUILD_ID:
      BUNDLE_LOCATION:
      BUNDLED_MODE:
      CORE_BUILD_ID:
      DEBUG:
      DOT_CICD_CLOUD_PROVIDER:
      DOT_CICD_PATH:
      DOT_CICD_PERSIST:
      DOT_CICD_TARGET:
      GITHUB_USER:
      GITHUB_USER_TOKEN:
      SIDECAR_ARGS:
      WAIT_DB_FOR:
      WAIT_DOTCMS_FOR:
      CORE_WEB_BUILD_ID:
    depends_on:
      - dotcms-app
    volumes:
      - /dev/shm:/dev/shm
    # volumes:
    #   - type: bind
    #     source: .
    #     target: /zap/wrk
    #     read_only: false
