
FROM owasp/zap2docker-stable:latest as build-scan

USER root

WORKDIR /zap

RUN apt-get update -y && apt-get install -y sudo jq iputils-ping lsof dnsutils

COPY build-src/entrypoint.sh /zap/entrypoint.sh
COPY build-src/runZapX.sh /zap/runZapX.sh
COPY build-src/runBaseline.sh /zap/runBaseline.sh
COPY build-src/runFullScan.sh /zap/runFullScan.sh
COPY build-src/runApiScan.sh /zap/runApiScan.sh
COPY build-src/baseline.conf /zap/baseline.conf
COPY build-src/api.conf /zap/api.conf
COPY build-src/application.wadl-Swagger20.json /zap/application.wadl-Swagger20.json
COPY build-src/scanResultsHeader.html /zap/scanResultsHeader.html
COPY build-src/scanResultsFooter.html /zap/scanResultsFooter.html
COPY setup/build-src/githubCommon.sh /zap/githubCommon.sh
COPY setup/build-src/testResults.sh /zap/testResults.sh

FROM cicd-dotcms

USER 0

WORKDIR /zap

ENV ZAP_PORT=8090

RUN apk --no-cache update \
    && apk upgrade \
    && apk add --no-cache git python3 \
    && ln -sf python3 /usr/bin/python
RUN python3 -m ensurepip
RUN pip3 install --no-cache --upgrade pip setuptools

COPY setup/build-src/forkDotcms.sh /srv/forkDotcms.sh
RUN chmod 500 /srv/forkDotcms.sh
COPY setup/build-src/stopDotcms.sh /srv/stopDotcms.sh
RUN chmod 500 /srv/stopDotcms.sh
COPY build-src/entrypoint.sh /srv/customEntrypoint.sh
RUN chmod 500 /srv/customEntrypoint.sh

COPY --from=build-scan /zap/ /zap/

RUN echo 'local.dotcms.site  127.0.0.1' >> /etc/hosts

ENTRYPOINT ["/srv/forkDotcms.sh"]
CMD ["dotcms"]
