# https://docs.docker.com/compose/compose-file/compose-versioning/
version: "3.7"

# https://docs.docker.com/compose/compose-file/

services:

  sidecar:
    image: "${SIDECAR_APP_IMAGE_NAME}"
    ports:
      - 8090:8090
    environment:
      BUILD_ID:
      BUILD_HASH:
      GITHUB_USER:
      GITHUB_USER_TOKEN:
      DOT_CICD_PATH:
      DOT_CICD_CLOUD_PROVIDER:
      DOT_CICD_PERSIST:
      DOT_CICD_TARGET:
      WAIT_DOTCMS_FOR:
      DEBUG:
    depends_on:
      - dotcms-app
    volumes:
      - type: bind
        source: .
        target: /zap/wrk
        read_only: false
